# fly.toml app configuration file generated for monfuse-telegram-bot on 2025-04-11T17:54:19+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'monfuse-telegram-bot'
primary_region = 'fra'

[processes]
app = "run --allow-net ./main.ts"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
